# Generated by Django 3.1.7 on 2021-03-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0002_auto_20210305_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('office_secretary', 'Office Secretary'), ('student', 'Student')]},
        ),
    ]
