# Generated by Django 3.1.7 on 2021-04-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0012_auto_20210402_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
    ]
