# Generated by Django 3.1.7 on 2021-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0013_remove_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='date_closed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='date_opened',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FIRST'), (2, 'SECOND')], null=True),
        ),
    ]
