# Generated by Django 3.1.7 on 2021-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0014_auto_20210403_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'STUDENT'), (1, 'OFFICE_SECRETARY'), (2, 'FINANCE')], null=True),
        ),
    ]
