# Generated by Django 3.1.7 on 2021-04-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0015_auto_20210406_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-date_opened']},
        ),
    ]
