# Generated by Django 3.1.7 on 2021-03-22 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0011_location'),
        ('office_app', '0005_auto_20210320_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alternative_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qr_attendance_app.location'),
        ),
    ]
