# Generated by Django 3.1.7 on 2021-04-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0012_auto_20210402_0043'),
        ('office_app', '0006_auto_20210323_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_datetime_from']},
        ),
        migrations.AddField(
            model_name='event',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qr_attendance_app.term'),
        ),
    ]
