# Generated by Django 3.1.7 on 2021-04-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0014_auto_20210403_0221'),
        ('office_app', '0009_attendance_clearance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='office_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='clearance',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qr_attendance_app.term'),
        ),
    ]
