# Generated by Django 3.1.7 on 2021-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0010_auto_20210405_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='is_misc',
            field=models.BooleanField(default=False),
        ),
    ]
