# Generated by Django 3.1.7 on 2021-04-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0012_clearance_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
