# Generated by Django 3.1.7 on 2021-03-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0004_auto_20210305_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_of_birth',
        ),
    ]
