# Generated by Django 3.1.7 on 2021-03-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0005_remove_client_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('S', 'STUDENT'), ('O', 'OFFICE SECRETARY'), ('H', 'HEAD')], null=True),
        ),
    ]
