# Generated by Django 3.1.7 on 2021-03-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0006_auto_20210305_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'STUDENT'), (1, 'OFFICE_SECRETARY'), (2, 'HEAD')], null=True),
        ),
    ]
