# Generated by Django 3.1.7 on 2021-03-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance_app', '0009_auto_20210314_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='course',
        ),
    ]
