# Generated by Django 3.1.7 on 2021-03-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0003_event_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_datetime',
            new_name='event_datetime_from',
        ),
        migrations.AddField(
            model_name='event',
            name='event_datetime_to',
            field=models.DateTimeField(null=True),
        ),
    ]
